import '@/css/globals.css';

import { Viewport, Metadata } from 'next';

import Navigation from '@/components/navigation';

export const viewport: Viewport = {
  themeColor: 'black',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  minimumScale: 1,
  userScalable: false,
  viewportFit: 'auto',
  colorScheme: 'dark'
};

export const metadata: Metadata = {
  title: {
    template: '%s | Next@14',
    default: 'Next@14'
  },
  description: 'Generated by Next.js'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='min-w-80'>
        <main className='flex flex-col md:flex-row'>
          <Navigation />

          <section className='p-5'>{children}</section>
        </main>
      </body>
    </html>
  );
}
