import '../scss/reset.scss';
import '../scss/layout-root.scss';

import { Metadata } from 'next';

import Navigation from '../components/navigation';

export const metadata: Metadata = {
  title: {
    template: '%s | Next@14',
    default: 'Next@14'
  },
  description: 'Generated by Next.js'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <main>
          <Navigation />

          <section>{children}</section>
        </main>
      </body>
    </html>
  );
}
